### ISSUE TITLE
Linux won't support the pawn-build - needs to have wine configured

### ISSUE THREAD

**Issue by dennorske** [dennorske/atom-pawn-build#2]
## Windows Application not supported on Ubuntu
Would need ability to run the pawncc.exe with wine on Linux.

`exec wine "~/.wine/drive_c/My/program.exe" "-argument(s)"`

### Steps to reproduce

1. ... Open Pawn file on Ubuntu
2. ... Compile it, and have fun watching a red pop up saying that something went wrong.

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.04.2
**Thrown From**: [pawn-build](https://github.com/frxstrem/atom-pawn-build) package 0.2.3

### Stack Trace

Uncaught Error: spawn EACCES

```
At internal/child_process.js:313

Error: spawn EACCES
    at exports._errnoException (util.js:1026:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at Object.exports.spawn (child_process.js:392:9)
    at Object.build (/packages/pawn-build/lib/pawn-build.coffee:67:29)
    at /packages/pawn-build/lib/pawn-build.coffee:29:84)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -4:07.9.0 core:select-all (input.hidden-input)
  2x -3:33 core:confirm (input.hidden-input)
     -3:10 core:backspace (input.hidden-input)
  2x -2:30.2.0 find-and-replace:show (input.hidden-input)
  3x -2:08.1.0 find-and-replace:find-next (input.hidden-input)
     -2:05.2.0 editor:consolidate-selections (input.hidden-input)
     -2:05.2.0 core:cancel (input.hidden-input)
     -2:03.3.0 find-and-replace:show (input.hidden-input)
     -2:00.0 core:confirm (input.hidden-input)
  4x -1:47 find-and-replace:find-next (input.hidden-input)
  3x -1:43.8.0 core:confirm (input.hidden-input)
     -1:33.7.0 application:add-project-folder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -1:25.4.0 pawn-build:build (input.hidden-input)
     -0:57.1.0 core:backspace (input.hidden-input)
     -0:13.4.0 core:paste (input.hidden-input)
     -0:05.8.0 pawn-build:build (input.hidden-input)
```

### Non-Core Packages

```
language-lisp 0.2.0 
pawn-build 0.2.3 
```

- Possible to get support for wine configurations as well?

**Comment by frxstrem** [comment]
In the package configuration, try setting:

 * **Path to pawncc executable** to `wine`
 * **Pawn options** to `C:\path\to\pawncc.exe, -d1, -(, -;`

This should run the command `wine C:\path\to\pawncc.exe -d1 -( - <file>` when building.

**Comment by dennorske** [comment]
Will test this whenever I'm back in Linux.

**Comment by frxstrem** [comment]
**TRANSFERED REPOSITORY TO [dennorske](https://github.com/dennorske)**
