### ISSUE TITLE
Failed to activate the pawn-build package

### ISSUE THREAD

**Issue by charcoast** [dennorske/atom-pawn-build#5]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.27.2 x64
**Electron**: 1.7.15
**OS**: Unknown Windows version
**Thrown From**: [pawn-build](https://github.com/dennorske/atom-pawn-build) package 0.3.0

### Stack Trace

Failed to activate the pawn-build package

```
At Cannot find module 'atom-message-panel'

Error: Cannot find module 'atom-message-panel'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.27.2/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.27.2/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.27.2/resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-pawn-build-0.3.0/lib/pawn-build.js:5:48)
    at /packages/atom-pawn-build-0.3.0/lib/pawn-build.js:181:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.27.2/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.27.2/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.27.2/resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.27.2/resources/app/src/package.js:782:33)
    at Package.activateNow (~/AppData/Local/atom/app-1.27.2/resources/app/src/package.js:220:40)
    at activationCommandSubscriptions.add.commandRegistry.onWillDispatch.event (~/AppData/Local/atom/app-1.27.2/resources/app/src/package.js:865:28)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.27.2/resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.27.2/resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.27.2/resources/app/src/command-registry.js:360:24)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.27.2/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.27.2/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.27.2/resources/app/src/window-event-handler.js:110:40)
```

### Commands

```
     -1:14.2.0 pawn-build:build (input.hidden-input)
  2x -0:06.8.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
pawn-build 0.3.0 
language-pawn 0.6.0 
```

**Comment by lumiuko** [comment]
Same here. The compiler just doesn't open when I press F5

**Comment by dennorske** [comment]
I'll take a look at this

**Comment by charcoast** [comment]
http://forum.sa-mp.com/showthread.php?t=550365

I found this (^) tutorial in SA-MP forum. It works very well. 

You just need to have the compiler to work

**Comment by dennorske** [comment]
Closing this and following up on #6
